/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 03:57:39 GMT 2022
 */

package ucm.yifei.tooltfm;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ucm.yifei.tooltfm.example.Test446;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Test446_ESTest extends Test446_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Test446.t(1085, 1085);
      assertEquals(1085, int0);
      int int1 = Test446.t(1003, 0);
      assertEquals(0, int1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Test446.t((-3100), (-3100));
      int int0 = (-683);
      Test446.t((-3100), (-683));
      Test446.t(0, (-683));
      int int1 = 1;
      Test446.t(1, (-683));
      // Undeclared exception!
      Test446.t((-3099), 0);
  }
}
