/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 03 21:34:34 GMT 2022
 */

package ucm.yifei.tooltfm;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import ucm.yifei.tooltfm.example.Test280;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Test280_ESTest extends Test280_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Test280 test280_0 = new Test280();
      int[] intArray0 = new int[1];
      int[] intArray1 = test280_0.moverUno(intArray0);
      assertArrayEquals(new int[] {(-1)}, intArray1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Test280 test280_0 = new Test280();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        test280_0.moverUno(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("ucm.yifei.tooltfm.example.Test280", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Test280 test280_0 = new Test280();
      // Undeclared exception!
      try { 
        test280_0.moverUno((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // NullPointerException
         //
         verifyException("ucm.yifei.tooltfm.example.Test280", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Test280 test280_0 = new Test280();
      int[] intArray0 = new int[5];
      int[] intArray1 = test280_0.moverUno(intArray0);
      assertArrayEquals(new int[] {(-1), 0, 0, 0, 0}, intArray1);
  }
}
