/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 14 20:46:32 GMT 2022
 */

package ucm.yifei.tooltfm.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ucm.yifei.tooltfm.example.Test21;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Test21_ESTest extends Test21_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Test21 test21_0 = new Test21();
      // Undeclared exception!
      try { 
        test21_0.cal((-1700), (-1700), (-6367), (-6367), (-1700));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1700
         //
         verifyException("ucm.yifei.tooltfm.example.Test21", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Test21 test21_0 = new Test21();
      // Undeclared exception!
      try { 
        test21_0.cal((-3573), 8, 0, 0, (-28));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -3573
         //
         verifyException("ucm.yifei.tooltfm.example.Test21", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Test21 test21_0 = new Test21();
      int int0 = test21_0.cal(0, (-4115), (-223), 9, 1891);
      assertEquals(4124, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Test21 test21_0 = new Test21();
      int int0 = test21_0.cal(0, 0, 0, 0, 1300);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Test21 test21_0 = new Test21();
      int int0 = test21_0.cal((-2712), 3404, (-2712), 0, (-2712));
      assertEquals((-3404), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Test21 test21_0 = new Test21();
      int int0 = test21_0.cal(0, (-2780), (-2320), 0, 0);
      assertEquals(2780, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Test21 test21_0 = new Test21();
      // Undeclared exception!
      try { 
        test21_0.cal((-2320), 0, 1, (-2780), 1300);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2320
         //
         verifyException("ucm.yifei.tooltfm.example.Test21", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Test21 test21_0 = new Test21();
      // Undeclared exception!
      try { 
        test21_0.cal(0, 0, 2047, 0, 3168);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 13
         //
         verifyException("ucm.yifei.tooltfm.example.Test21", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Test21 test21_0 = new Test21();
      // Undeclared exception!
      try { 
        test21_0.cal((-1508), (-1508), (-3057), (-1508), (-3057));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1508
         //
         verifyException("ucm.yifei.tooltfm.example.Test21", e);
      }
  }
}
